//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Paaaword { get; set; }
        public int IsActive { get; set; }
    }
}
